### ISSUE TITLE
USER STORY: Inital Setup #12

### ISSUE THREAD

**Issue by FarisGJD** [FarisGJD/skincared#13]
As a **developer**, I can **I can setup Django and install the supporting libraries and packages I need**, so that **so i can start the development process.**

## Tasks
- [x] Task 1  - Install Django
- [x] Task 2 -  Install dj_database_url psycopg2 
- [x] Task 3 - Install Pillow 
- [x] Task 4 - Install Django allauth 
- [x] Task 5 - Install Stripe 
- [x] Task 6 - Install Django Crispy Forms 
- [x] Task 7 - Install Django Countries 
- [x] Task 8 - Install Gunicorn 
- [x] Task 9 - Create Procfile 
- [x] Task 10 - Create requirements.txt
- [x] Task 11 - Create the Django project
- [x] Task 12 - Create a Superuser 
- [x]  Task 13 - Create main Tempalte folder 
- [x]  Task 14 - Create first app (home)
