### ISSUE TITLE
USER STORY: View landing page and use navigation menu #14

### ISSUE THREAD

**Issue by FarisGJD** [FarisGJD/skincared#15]
As a **user**, I can **head to the site's landing page and use its navigation menu**so that **I can traverse the website in the hopes of buying something. **

## Tasks
- [x] Task 1 - Create a landing page (index.html) in the home app with its relevant Views and URLs
- [x] Task 2 - Create a navigation menu within the root templates folder 
- [x] Task 3 - Add JS  to handle using the header navigation and footer
