### ISSUE TITLE
USER STORY: View product, brand and general site offerings #16 

### ISSUE THREAD

**Issue by FarisGJD** [FarisGJD/skincared#17]
As a **user**, I can **checkout SkinCareds product lines as well as the brands that they house and more information about skincare**, so that **I can make an informed purchase. **

## Tasks
- [x] Task 1 - Create Brand, Product Type, Skin Type & Skincare models to be rendered and manipulated on the site
- [x] Task 2 - Customise the Admin panel to reflect this 
- [x] Task 3 - Load the data in your fixtures folder onto the admin panel 
- [x] Task 4 - Create all products view and products details view with relevant URLs  
- [x] Task 5 - Create all brands and brands details view with relevant URLs  
- [x] Task 6 - Create skin type view with relevant URLs
