### ISSUE TITLE
USER STORY: Use bag to house and manage current or future items I am purchasing #18 

### ISSUE THREAD

**Issue by FarisGJD** [FarisGJD/skincared#19]
As a **user**, I can **manage and house the items I am interested in purchasing at one location**so that **I can continue to the checkout menu now or in the future.**

## Tasks
- [x] Task 1 - Create bag view with relevant URL's 
- [x] Task 2 - In the bag view give the user full CRUD functionality
- [x] Task 3 - Create context file that will handle the bag apps logic (e.g. delivery total, bag items, product count etc...) 
- [x] Task 4 - Create bag template that will render the logic created in the view and context files
