### ISSUE TITLE
USER STORY: <TITLE>

### ISSUE THREAD

**Issue by FarisGJD** [FarisGJD/skincared#2]
As a **developer**, I can **get my workspace fully functioning including basic installs**, so that **start coding and deploy my project early to Heroku. **

## Tasks
- [ ] Task 1 - Install Django==3.2 and gunicorn 
- [ ] Task 2 - Install dj_database_url==0.5.0 and psycopg2
- [ ] Task 3 - Create / freeze requirements.txt file 
- [ ] Task 4 - Create gitignore file and add sqlite3 and .pyc
- [ ] Task 5 - Make initial migrations 
- [ ] Task 6 - Create super user
