### ISSUE TITLE
USER STORY: Initial Django Workspace Setup 

### ISSUE THREAD

**Issue by FarisGJD** [FarisGJD/skincared#2]
As a **developer**, I can **setup Django and other libraries, file and folder structure**, so that **I can start to write code for SkinCared**

## Tasks
- [ ] Task 1 - Install Django 
- [ ] Task 2 - Create SkinCared project folder through django-admin
- [ ] Task 3 - Create and add relevant files to gitignore 
- [ ] Task 4 - Create superuser
- [ ] Task 5 -
