### ISSUE TITLE
USER STORY: Complete the checkout process, purchasing skincare products #20 

### ISSUE THREAD

**Issue by FarisGJD** [FarisGJD/skincared#21]
As a **user**, I can **continue the purchase process from the bag to the checkout**, so that **I can purchase my items.**

## Tasks
- [x] Task 1 - Create order and order line item models that will handle the checkout process such as generate order number, update total and save user details
- [x] Task 2 - Create a form that will take the users details for delivery purposes and save them if desired 
- [x] Task 3 - Create apps and signals file and logic
- [x] Task 4 - Render and customise checkout models for the admin 
- [x] Task 5 - Render the checkout apps models and aforementioned logic to a checkout and checkout success template
