### ISSUE TITLE
USER STORY: Checkout securely using Stripe payment system #22 

### ISSUE THREAD

**Issue by FarisGJD** [FarisGJD/skincared#23]
As a **user**, I can **make a secure purchase with my card details**, so that **my sensitive information stays private and I can build trust with SkinCared.**

## Tasks
- [x] Task 1 - Apply Stripes secure payment logic 
- [x] Task 2 - Use Stripes UI element so that it fits the overall style of the site (js & css) 
- [x] Task 3 -  Give the user feedback at each stage of the payment process
- [x] Task 4 - Apply Stripe webhooks so that the owner of the site can check for verified purchases as well as send confirmation emails to users
