### ISSUE TITLE
USER STORY: Create or login to an existing profile that is customised to me #24 

### ISSUE THREAD

**Issue by FarisGJD** [FarisGJD/skincared#26]
As a **user**, I can **signup or log in to an existing account**, so that **I can look at my historical purchases as well as update my contact info.*

## Tasks
- [x] Task 1 - Create  a user profile model  that will handle CRUD in terms of the user's personal information and store historical orders 
- [x] Task 2 -  Create a form that will handle the aforementioned CRUD functionality 
- [x] Task 3 - Render the previous logic to the profile template with relevant URLs 
- [x] Task 4 -  Customise files in allauth account folder (emails, login, logout, passwords, signup and verification)
