### ISSUE TITLE
USER STORY: Ability to manipulate the admin from the live site #25 

### ISSUE THREAD

**Issue by FarisGJD** [FarisGJD/skincared#27]
As a **site owner**, I can **perform full CRUD functionality on the server side**, so that **I can manipulate the database easily.**

## Tasks
- [x] Task 1 - Create a product form that will handle admin's CRUD functionality
- [x] Task 2 - Apply this logic and render it to an additional product and update product template respectively 
- [x] Task 3 - Add update and delete links to relevant parts of the site, making sure to use Django superuser to limit access to users
