### ISSUE TITLE
USER STORY: Implement signup form and descriptive meta tags #28 

### ISSUE THREAD

**Issue by FarisGJD** [FarisGJD/skincared#29]
As a **site owner**, I can **include a signup form building my list of contacts and add descriptive meta tags**, so that **I can directly communicate with my consumers and achieve higher rankings in search results.**

## Tasks
- [x] Task 1 - Use MailChimp and add their custom code to the site 
- [x] Task 2 - Include SkinCared Facebook business page in the <a> footer
- [x] Task 3 - Use SEO techniques such as <strong> and semantic html aswell as descriptive meta tags
