### ISSUE TITLE
USER STORY: Setup Allauth & Configure Workspace

### ISSUE THREAD

**Issue by FarisGJD** [FarisGJD/skincared#4]
As a **user**, I can **log in or create an account**, so that **as a new user i can purchase products or as an exiting user I can purchase products faster**. 

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that
	**When** the
	**Then**
- Acceptance Criteria 2
	**Given** that
	**When** the
	**Then**
- Acceptance Criteria 3
	**Given** that
	**When** the
	**Then**
- Acceptance Criteria 4
	**Given** that
	**When** the
	**Then**

## Tasks
- [ ] Task 1 - Install allatuth 
- [ ] Task 2 - Update settings.py per allauth documentation and urls.py 
- [ ] Task 3 - Freeze package to requirements.txt
- [ ] Task 4 - Create a top-level templates directory with an allauth directory nested inside
- [ ] Task 5 - Copy all the allatuh templates you need in the aforementioned directory
