### ISSUE TITLE
USER STORY: Install  & Setup Allauth 

### ISSUE THREAD

**Issue by FarisGJD** [FarisGJD/skincared#4]
As a **user**, I can **create and maintain an account with SkinCared**, so that **I can order and purchase items without having to enter my details each time**. 

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that
	**When** the
	**Then**
- Acceptance Criteria 2
	**Given** that
	**When** the
	**Then**
- Acceptance Criteria 3
	**Given** that
	**When** the
	**Then**
- Acceptance Criteria 4
	**Given** that
	**When** the
	**Then**

## Tasks
- [ ] Task 1 - Install Django allauth
- [ ] Task 2 - Update SkinCared settings.py file with relevant allauth settings per documentation
- [ ] Task 3 - Customise SkinCared settings.py file pertaining to account registration and authentication 
- [ ] Task 4 - Include allauth URLs in SkinCared urls.py file 
- [ ] Task 5 - Create requirements.txt file 
- [ ] Task 6 - Create allauth templates directory
