### ISSUE TITLE
USER STORY: Create base.html Template 

### ISSUE THREAD

**Issue by FarisGJD** [FarisGJD/skincared#6]
As a **user**, I can **access SkinCared navigation, social media accounts and contact information**, so that **I can explore the site to purchase products as well as see what SkinCared is about and contact them if need be**. 

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that
	**When** the
	**Then**
- Acceptance Criteria 2
	**Given** that
	**When** the
	**Then**
- Acceptance Criteria 3
	**Given** that
	**When** the
	**Then**
- Acceptance Criteria 4
	**Given** that
	**When** the
	**Then**

## Tasks
- [ ] Task 1 - Create base.html template within the templates directory. 
- [ ] Task 2 - Create the SkinCared logo and navigation menu.
- [ ] Task 3 - Create the footer and give access to social media accounts as well as contact information. 
- [ ] Task 4
