### ISSUE TITLE
USER STORY: Create Home App & Add Relevant Files & Settings

### ISSUE THREAD

**Issue by FarisGJD** [FarisGJD/skincared#7]
As a **user**, I can **access the home page**, so that **I can see what SkinCared has to offer**. 

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that
	**When** the
	**Then**
- Acceptance Criteria 2
	**Given** that
	**When** the
	**Then**
- Acceptance Criteria 3
	**Given** that
	**When** the
	**Then**
- Acceptance Criteria 4
	**Given** that
	**When** the
	**Then**

## Tasks
- [ ] Task 1 - Create Home app and a templates directory inside.
- [ ] Task 2 - Create index.html file that will act as the home page inside the home app.
- [ ] Task 3 - Render the index file within the Home app's view.py file as well as create a new urls.py file to render the home view. 
- [ ] Task 4 - Add a Path to the home view in the SkinCared urls.py file and update the relevant settings.py to reflect relevant changes.
