### ISSUE TITLE
USER STORY: Customise base.html template 

### ISSUE THREAD

**Issue by FarisGJD** [FarisGJD/skincared#7]
As a **developer**, I can **organise my base.html template**, so that **I can customise SkinCared to my vision**. 

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that
	**When** the
	**Then**
- Acceptance Criteria 2
	**Given** that
	**When** the
	**Then**
- Acceptance Criteria 3
	**Given** that
	**When** the
	**Then**
- Acceptance Criteria 4
	**Given** that
	**When** the
	**Then**

## Tasks
- [ ] Task 1 - Create different blocks for different data to be rendered
- [ ] Task 2 - Add CDN's such as Font Awesome, Google Material Icons, jQuery & Bootstrap
- [ ] Task 3 - Include blocks for custom CSS and JS in the header and bottom of the body respectively
