### ISSUE TITLE
USER STORY: Create Navigation Menu

### ISSUE THREAD

**Issue by FarisGJD** [FarisGJD/skincared#9]
As a **user**, I can **use SkinCared navigation menu**, so that **i can search for specific products or find something new**. 

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that
	**When** the
	**Then**
- Acceptance Criteria 2
	**Given** that
	**When** the
	**Then**
- Acceptance Criteria 3
	**Given** that
	**When** the
	**Then**
- Acceptance Criteria 4
	**Given** that
	**When** the
	**Then**

## Tasks
- [ ] Task 1 - Create an includes folder
- [ ] Task 2 - Create a navigation menu for both big and small screens. 
- [ ] Task 3 - User media queries to adjust sizing as appropriate. 
- [ ] Task 4 - Create JavaScript for the drop-down menu on the nav bar for big screens.
